### ISSUE TITLE
图片异步检测 - java.lang.NoClassDefFoundError: Could not initialize class com.netease.yidun.sdk.core.endpoint.DefaultEndpointResolver$InstanceHolder

### ISSUE THREAD

**Issue by bububear** [yidun/yidun-java-sdk#2]
springboot 、maven、idea

一直找不到这个类，是缺失什么配置吗？

![image](https://user-images.githubusercontent.com/35417310/204819917-f8c66b8a-2646-4eed-81e0-6532d3458984.png)

**Comment by tonyd1989** [comment]
不需要做任何配置的，maven的pom文件引入sdk的dependency能发下吗

**Comment by bububear** [comment]
> 

问题已解决，原因是依赖的 gson 版本冲突。
